/*
 * generated by Xtext
 */
package org.erlide.scoping;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.SimpleLocalScopeProvider;
import org.erlide.project.model.IErlangModel;

/**
 * This class contains custom scoping description.
 *
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping on
 * how and when to use it
 *
 */
public class ErlangScopeProvider extends SimpleLocalScopeProvider {
    IErlangModel model;

    @Override
    public IScope getScope(final EObject context, final EReference reference) {
        // TODO Auto-generated method stub
        return super.getScope(context, reference);
    }
}
