/*
 * generated by Xtext
 */
package org.erlide.ui.outline;


/**
 * customization of the default outline structure
 * 
 */
public class ErlangDebugOutlineTreeProvider extends ErlangOutlineTreeProvider {

    // protected boolean _isLeaf(FunctionClause c) {
    // return true;
    // }

    @Override
    protected void _createChildren(final Object parent, final Object element) {
        // TODO Auto-generated method stub
        super._createChildren(parent, element);
    }
}
