/*
 * generated by Xtext
 */
package org.erlide.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class ErlangOutlineTreeProvider extends DefaultOutlineTreeProvider {

	// protected boolean _isLeaf(FunctionClause c) {
	// return true;
	// }

	@Override
	protected void _createChildren(Object parent, Object element) {
		// TODO Auto-generated method stub
		super._createChildren(parent, element);
	}
}
