/*
 * generated by Xtext
 */
package org.erlide.ui.outline;


/**
 * customization of the default outline structure
 * 
 */
public class ErlangOutlineTreeProvider extends ErlangOutlineTreeProviderBase {

}
