/*
 * generated by Xtext
 */
package org.erlide.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;
import org.erlide.erlang.Form;
import org.erlide.erlang.FunRef;
import org.erlide.erlang.FunctionClause;
import org.erlide.erlang.Module;

/**
 * outline structure -- show elements as they are in the file
 * 
 */
public class SimpleErlangOutlineTreeProvider extends DefaultOutlineTreeProvider {

    protected boolean _isLeaf(final FunctionClause c) {
        return true;
    }

    protected boolean _isLeaf(final FunRef c) {
        return true;
    }

    protected void _createChildren(final DocumentRootNode parent,
            final Module module) {
        for (final Form element : module.getForms()) {
            createNode(parent, element);
        }
    }

}
