/*
 * generated by Xtext
 */
package org.erlide.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.erlide.services.ErlangGrammarAccess;

import com.google.inject.Inject;

public class ErlangParser extends
        org.eclipse.xtext.parser.antlr.AbstractAntlrParser {

    @Inject
    private ErlangGrammarAccess grammarAccess;

    @Override
    protected void setInitialHiddenTokens(final XtextTokenStream tokenStream) {
        tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
    }

    @Override
    protected org.erlide.parser.antlr.internal.InternalErlangParser createParser(
            final XtextTokenStream stream) {
        return new org.erlide.parser.antlr.internal.InternalErlangParser(
                stream, getGrammarAccess());
    }

    @Override
    protected String getDefaultRuleName() {
        return "Module";
    }

    public ErlangGrammarAccess getGrammarAccess() {
        return grammarAccess;
    }

    public void setGrammarAccess(final ErlangGrammarAccess grammarAccess) {
        this.grammarAccess = grammarAccess;
    }

}
