/*
 * generated by Xtext
 */
package org.erlide.parser.antlr;

import java.io.InputStream;

import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ErlangAntlrTokenFileProvider implements IAntlrTokenFileProvider {

    @Override
    public InputStream getAntlrTokenFile() {
        final ClassLoader classLoader = getClass().getClassLoader();
        return classLoader
                .getResourceAsStream("org/erlide/parser/antlr/internal/InternalErlang.tokens");
    }
}
