/*
 * generated by Xtext
 */
package org.erlide;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ErlangUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.erlide.ui.internal.ErlangActivator.getInstance().getInjector("org.erlide.Erlang");
	}
	
}
