/*
 * generated by Xtext
 */
package org.erlide.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.erlide.ui.internal.ErlangActivator;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ErlangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ErlangActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ErlangActivator.getInstance().getInjector(ErlangActivator.ORG_ERLIDE_ERLANG);
	}
	
}
