/*
 * generated by Xtext
 */
package org.erlide.validation;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.ComposedChecks;

@ComposedChecks(validators = {
        org.eclipse.xtext.validation.ImportUriValidator.class,
        org.eclipse.xtext.validation.NamesAreUniqueValidator.class })
public class AbstractErlangJavaValidator extends
        org.eclipse.xtext.validation.AbstractDeclarativeValidator {

    @Override
    protected List<EPackage> getEPackages() {
        final List<EPackage> result = new ArrayList<EPackage>();
        result.add(org.erlide.erlang.ErlangPackage.eINSTANCE);
        return result;
    }

}
